# Generated by Django 4.0.4 on 2022-04-15 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=48, null=True)),
                ('last', models.CharField(max_length=48, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=48)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=48, null=True)),
                ('last', models.CharField(max_length=48, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('abr', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('length', models.IntegerField()),
                ('country', models.CharField(max_length=48)),
                ('awards', models.TextField()),
                ('poster', models.URLField()),
                ('earnings', models.IntegerField()),
                ('actors', models.ManyToManyField(related_name='production_actors', to='omdb.actor')),
                ('audience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_audience', to='omdb.audience')),
                ('directors', models.ManyToManyField(related_name='production_directors', to='omdb.director')),
                ('genres', models.ManyToManyField(related_name='production_genres', to='omdb.genre')),
                ('languages', models.ManyToManyField(related_name='production_languages', to='omdb.language')),
                ('medium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_edium', to='omdb.medium')),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=48, null=True)),
                ('last', models.CharField(max_length=48, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=48)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('possible', models.IntegerField()),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omdb.production')),
            ],
        ),
        migrations.AddField(
            model_name='production',
            name='writers',
            field=models.ManyToManyField(related_name='production_writers', to='omdb.writer'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48)),
                ('description', models.TextField()),
                ('productions', models.ManyToManyField(blank=True, related_name='gallery_productions', to='omdb.production')),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
    ]
