# Generated by Django 4.0.4 on 2022-04-14 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='mediums',
            new_name='medium',
        ),
    ]
