# Generated by Django 4.0.4 on 2022-04-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.DateTimeField(auto_now=True)),
                ('content', models.JSONField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
