# Generated by Django 4.0.4 on 2022-04-14 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omdb', '0002_rename_mediums_series_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='medium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_edium', to='omdb.medium'),
        ),
        migrations.RemoveField(
            model_name='series',
            name='medium',
        ),
        migrations.AddField(
            model_name='series',
            name='medium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_medium', to='omdb.medium'),
        ),
    ]
