# Generated by Django 4.0.4 on 2022-04-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omdb', '0002_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
