# Generated by Django 4.0.4 on 2022-04-15 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omdb', '0003_alter_production_medium_remove_series_medium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='series',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
