# Generated by Django 4.0.4 on 2022-04-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omdb', '0004_remove_gallery_series_delete_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='productions',
            field=models.ManyToManyField(null=True, related_name='gallery_productions', to='omdb.production'),
        ),
    ]
